version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-cluster-7
      - discovery.type=single-node
      - xpack.security.enabled=$ELASTIC_SECURITY
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network


  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


volumes:
  es-data01:
    driver: local
    #external: true

networks:
  es-network:
    driver: bridge
    
    
